# Generated by Django 5.2.4 on 2025-07-09 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=50)),
                ('service_type', models.CharField(choices=[('Makeup', 'Makeup'), ('Photography', 'Photography'), ('Decor', 'Decor')], max_length=20)),
                ('event_date', models.DateField()),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Scheduled', 'Scheduled'), ('Closed', 'Closed')], default='New', max_length=20)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.salesrep')),
            ],
        ),
        migrations.CreateModel(
            name='CallSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField()),
                ('status', models.CharField(default='Scheduled', max_length=20)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.lead')),
                ('rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.salesrep')),
            ],
        ),
    ]
