# Generated by Django 5.2.4 on 2025-07-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
