# Generated by Django 5.0.4 on 2025-07-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_lead_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
